services:
  - type: web
    name: n8n-workflow
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
